### PR TITLE
A whole mess of updates and fixes.

### PR DESCRIPTION
**Pull request by JoeMattie**
Levels are now defined in the config file, not by player screen dimensions.

Food is pre-filtered to only send that which might be visible to the player(s).

A bunch of other stuff...

### CODE REVIEW

**Comment by neslinesli93** [comment]
As now there are a lot of unmerged PR, all very different from each other and all touch different aspects of the application.
I think it would be much better if you tried to do a PR with atomic commits, where each commit only touches/modifies one detail of the game, instead of having one very big -unreadable- commit.
This is just my opinion, but I think it can bring the development of this clone on a very bright path

**Comment by Buskcoin** [comment]
Cool, does this solve the problem of getting stuck in the boundries? i was trying to figure that one out. I agree with neslinesli93 about breaking it up.

**Comment by JoeMattie** [comment]
Sorry for the messy commit, I'll redo and submit a new pull request.

**Comment by JoeMattie** [comment]
Closing pull request.  Resubmitted as PR:186

**Pull request closed without merging**
