### PR TITLE
Es6 refactor

### PR DESCRIPTION
**Pull request by thomashqwerty**

### CODE REVIEW

**Comment by IgorAntun** [comment]
@abalabahaha What do you think?

**Comment by huytd** [comment]
It's a right time for a big change now! :+1:

**Comment by IgorAntun** [comment]
@thomashqwerty Could you please take a look at that merge conflict so we can move forward? :D

**Comment by jollesnaas** [comment]
Please add bots, otherwise I am so alone?

**Comment by abalabahaha** [comment]
The diff looks really messed up with this one.

**Comment by abalabahaha** [comment]
@IgorAntun I think you need to read this again. What I see is he's merging the un-updated abandoned es6-refactor branch, which is about 6 months old now.

**Comment by abalabahaha** [comment]
Also, refactoring to es6 makes the project incompatible with NodeJS versions lower than 4.0.0. If you guys think that's fine, I might start refactoring the current master sometime soon.

**Comment by jamesmou** [comment]
@abalabahaha You guys are almost done making the viruses, and map? I know it takes time, but when will the versions be updated. Thx

**Comment by jamesmou** [comment]
Also is there a way to stop from kicking you, because it says the heartbeats thing.

**Comment by abalabahaha** [comment]
@jamesmou This isn't exactly the best place to ask such questions... Better off on the Gitter

AFAIK nobody is working on viruses or the map. It's up to whoever feels like it.

Just increase the heartbeat interval to a higher number to prevent it kicking too often.

**Pull request closed without merging**
