### PR TITLE
Structure

### PR DESCRIPTION
**Pull request by kbariotis**
This addresses #9.

What do you think?

### CODE REVIEW

**Comment by IgorAntun** [comment]
Looks awesome, a great headstart to reestructuring it :)
You might as well want to include yourself as a contributor in `package.json` :P

**Comment by D3VONT3CH** [comment]
good job, i am trying on my server.

**Comment by D3VONT3CH** [comment]
Error 503 for me
https://pillo-nibro.rhcloud.com/

**Comment by huytd** [comment]
Thank you so much @kbariotis :+1: 
Please feel free to add yourself as the contributor in `package.json`

**Comment by huytd** [comment]
But we need to check the 503 issue on @D3VONT3CH 's server first :D

**Comment by IgorAntun** [comment]
That 503 probably just means his node server is offline. Probably exited because of some error.

**Comment by D3VONT3CH** [comment]
i think has a conflict and/or error in code.

**Comment by huytd** [comment]
still looking for a way to merge this pull request :sob:

**Comment by huytd** [comment]
Done :D

**Pull request merged**
