### PR TITLE
First attempt of a binary protocol

### PR DESCRIPTION
**Pull request by neslinesli93**
Opening this for visibility, because it's in such an early stage it's embarassing.
However my experience with websockets and socket.io is very limited, so I don't know why the server raises a TypeError as soon as the client emits a 'gotit'.
If anyone has a clue on what's happening under the hood, don't be shy :)
EDIT: Before you ask, I had to commit the node/bower modules because heroku was giving me a strange gulp error which could be resolved this (shitty) way.

### CODE REVIEW

**Comment by IgorAntun** [comment]
It seems like there are a few merge conflicts, could you please solve those so I can merge this PR? Thank you! :)

Another suggestion would be closing this PR and opening a new one without that node/bower modules mess haha :P

**Comment by neslinesli93** [comment]
Yeah, I submitted this PR just for people to see my attempt of doing a binary protocol and what were the tradeoffs of using socket.io
No way this PR has to be merged in the project, it literally breaks everything!

**Comment by giongto35** [comment]
Nice attempt. It gave me some insight about binary packet sending. I will take a look at it and try my best to fix it.

**Comment by IgorAntun** [comment]
I wonder, any updates on this? Anyone else working on a binary protocol?

**Comment by abalabahaha** [comment]
I've started an _attempt_ on binary stuffs. But, as the project currently stands, quite a bit of it will need rewriting to work/work better with binary data, so no promises.

**Comment by Buskcoin** [comment]
:thumbsup:

**Comment by IgorAntun** [comment]
Cool :)

**Comment by testtest12** [comment]
HEy  don't know shit about coding and java.. can you please make an exe or something for client and server.. if this is still not finished then im sorry

**Comment by abalabahaha** [comment]
@testtest12 Would be better if you had made an issue for this, but whatever. I modified issue #282 to include your request The project is by no means finished, just that everybody has been busy recently, but that is on the list now.

**Comment by abalabahaha** [comment]
Is it still necessary to keep this open?

**Pull request closed without merging**
