### PR TITLE
experimental webgl frontend

### PR DESCRIPTION
**Pull request by JoeMattie**
Please take a look and let me know if you think this has promise.  This PR CAN'T be merged in its present state, but has some spiffy webgl stuff I thought you guys might want to check out.

### CODE REVIEW

**Comment by IgorAntun** [comment]
Very interesting, good job! Is it compatible with all major browsers/os's though?

**Comment by JoeMattie** [comment]
It can fallback to canvas  or svg, so... Yes?

**Comment by IgorAntun** [comment]
Awesome :)

**Comment by JoeMattie** [comment]
@IgorAntun take a look at it now, I fixed a bunch of stuff and added a parallax background :)

**Pull request closed without merging**
