### PR TITLE
Database integration

### PR DESCRIPTION
**Pull request by flaminggenius**
It took me like 5-6 hours of experimenting and bug fixes but I FINALLY got it working so a breakdown

I added sql settings into config.json so that people can modify to their needs easily

Added code to server to connect to database based on settings in config.json

Added code to log incorrect password input for admin (it was on the todo list)

This could really be useful for the future as well with a level/xp system I would start working on it but....I just spent like 5 hours on all this.....coffee and code || sleep
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Max1Truc%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/flaminggenius%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/14892313%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/vikramdurai%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/7627362%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-262897851%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-11-25T07%3A44%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/14892313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/flaminggenius%22%7D%7D%2C%20%7B%22body%22%3A%20%22Anybody%20looking%20at%20this%3F%22%2C%20%22created_at%22%3A%20%222016-11-26T00%3A49%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/14892313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/flaminggenius%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20am.%22%2C%20%22created_at%22%3A%20%222016-12-10T06%3A30%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/7627362%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vikramdurai%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-12-10T07%3A09%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/7627362%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vikramdurai%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-03-23T21%3A39%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Max1Truc%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hey%2C%20huytd%2C%20are%20you%20looking%20at%20this%20%3F%5Cr%5CnIt%27s%20OKAY%20%21%22%2C%20%22created_at%22%3A%20%222017-03-23T21%3A43%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Max1Truc%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cud83d%5Cudc4d%20%20Thanks%20everybody%21%20Merging%21%22%2C%20%22created_at%22%3A%20%222017-03-23T22%3A17%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/613943%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/huytd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-262897851%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-263036069%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-266182849%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-266184309%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-288868597%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-288869574%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/471%23issuecomment-288877515%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Max1Truc'></a><a href='https://github.com/flaminggenius'></a><a href='https://github.com/vikramdurai'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/huytd/agar.io-clone/pull/471#issuecomment-262897851'>General Comment</a></b>
- <a href='https://github.com/flaminggenius'></a> :shipit:
- <a href='https://github.com/flaminggenius'></a> Anybody looking at this?
- <a href='https://github.com/vikramdurai'></a> I am.
- <a href='https://github.com/vikramdurai'></a> :shipit:
- <a href='https://github.com/Max1Truc'></a> :shipit:
- <a href='https://github.com/Max1Truc'></a> Hey, huytd, are you looking at this ?
It's OKAY !
- <a href='https://github.com/huytd'></a> 👍  Thanks everybody! Merging!

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/471?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/471?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/471?approve=0'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/471'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/471'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by flaminggenius** [comment]
:shipit:

**Comment by flaminggenius** [comment]
Anybody looking at this?

**Comment by vikramdurai** [comment]
I am.

**Comment by vikramdurai** [comment]
:shipit:

**Comment by Max1Truc** [comment]
:shipit:

**Comment by Max1Truc** [comment]
Hey, huytd, are you looking at this ?
It's OKAY !

**Comment by huytd** [comment]
👍  Thanks everybody! Merging!

**Comment by Max1Truc** [comment]
cool !

**Comment by TheDiamondYT1** [comment]
@huytd You really need to learn to use the squash and merge button.

**Comment by huytd** [comment]
Yes master 🙇 

LOL, just kidding, I don't think Github has that button (at least, at the time I hit the merge), but yes, I should do it on the command line for big pull requests like this. 

👍

**Comment by TheDiamondYT1** [comment]
@huytd 
screenshot_2017-09-11-18-46-09

**Pull request merged**
