### PR TITLE
Fix app.json

### PR DESCRIPTION
**Pull request by JuhQ**
app.json did not contain valid json

### CODE REVIEW

**Comment by JuhQ** [comment]
Well shit, it seems that other stuff from my last pr is included here. Should not code directly to master..

**Comment by IgorAntun** [comment]
That app.json typo.... I'm dumb. Really dumb.

**Comment by JuhQ** [comment]
Shit happens when you party naked. :tada:

**Comment by IgorAntun** [comment]
So, safe to merge already?

**Comment by JuhQ** [comment]
Sure, the extra stuff is just for the gulp to print stuff more nicely to console.

**Comment by IgorAntun** [comment]
great :+1:

**Pull request merged**
