### PR TITLE
Fallback babel to ^.8.38 first, cc #428 #429

### PR DESCRIPTION
**Pull request by PeterDaveHello**
In #428, babel upgraded from v5 to v6 make a problem caused the app not work, so fallback to ^5.8.38 first, tested working. Let's make it work first, then see how to upgrade without breaking, maybe should also add more tests to increase the code coverage in test.

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/430'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by PeterDaveHello** [comment]
In #428, babel upgraded from v5 to v6 make a problem caused the app not work, so fallback to ^5.8.38 first, tested working. Let's make it work first, then see how to upgrade without breaking, maybe should also add more tests to increase the code coverage in test.

**Comment by abalabahaha** [comment]
I fixed the export issues in c710741, so this is not necessary anymore.

**Comment by PeterDaveHello** [comment]
Great :+1:

**Pull request closed without merging**
