### PR TITLE
Updated for Bluemix

### PR DESCRIPTION
**Pull request by juslee**
Updated Bluemix manifest.yml configurations to build, and use default generated Procfile "npm start" instead.
Updated gulpfile.js to ignore vendor/**/*.js for lint test. 
Updated Bluemix servers with the latest source code.

### CODE REVIEW

**Comment by IgorAntun** [comment]
Could you please fix the merge conflicts?

**Comment by Buskcoin** [comment]
Awesome, I'm excited to play with more people on bluemix US

**Comment by abalabahaha** [comment]
@juslee Reminder to fix merge conflicts

**Comment by abalabahaha** [comment]
Can be closed now, already merged.

**Pull request merged**
