### PR TITLE
Make chat more intuitive

### PR DESCRIPTION
**Pull request by ZeHaxor**
Makes more sense for incoming messages to rise from the input box.

### CODE REVIEW

**Comment by Ariamiro** [comment]
screenshot?

**Comment by ZeHaxor** [comment]
hard to screenshot without a recording;
previously, when you talked in that chat, the messages would come from the top of the box and push the others downwards.
This changes it so that new messages are added down the bottom and they push the old ones up.

**Comment by Ariamiro** [comment]
great work.

**Comment by IgorAntun** [comment]
Seems like you're deleting the previous messages that way? What about adding a y-overflow so people can scroll up and down the messages, and start deleting the previous once a limit of, say, 100 messages is hit?

**Comment by IgorAntun** [comment]
Ooops sorry for closing it, missclicked the button ;P

**Comment by Ariamiro** [comment]
i think that this is more economic.

**Comment by ZeHaxor** [comment]
I'm working on this.

**Comment by huytd** [comment]
Great @ZeHaxor ! Thank you so much
Please add yourself as a contributor in `package.json`

**Comment by huytd** [comment]
And please make a new pull request for the next fix (the scroll up feature)

**Pull request merged**
