### PR TITLE
My attempt at implemtenting a quadtree

### PR DESCRIPTION
**Pull request by Buskcoin**
I'm using a fork of [silflow's quadtree](https://github.com/silflow/quadtree-javascript). I wasn't sure where to put the quadtree.js file. As far I know it's working. Please review.

### CODE REVIEW

**Comment by Buskcoin** [comment]
I fixed the merge conflicts and moved quadtree.js in the main folder.

**Comment by IgorAntun** [comment]
That looks great :)

**Comment by MadaraUchiha** [comment]
Nice! I was going to put a quadtree myself. :+1:

**Comment by Buskcoin** [comment]
:)

**Pull request merged**
