### PR TITLE
Decreased max speed so it's like Original Agar.io

### PR DESCRIPTION
**Pull request by Crasha**
Decreased max speed from 20 to 7

### CODE REVIEW

**Comment by hunterpl** [comment]
Crash i just made a test and compared to agar.io and the value of speed should be a 10 if We want to make similar speed.

**Comment by Crasha** [comment]
@hunterpl Really? I thought 7 was nearly perfect. I first thought 10 yesterday but it was too fast. I had two tabs open, one with agar.io and one with OpenAgar, and changing it from 20 to 7, you could notice the similarities.

**Comment by IgorAntun** [comment]
Why isn't this line listening to the `config.json` maxSpeed variable?

**Comment by IgorAntun** [comment]
And by the way, that looks like an 8 there ;P

**Comment by hunterpl** [comment]
@IgorAntun Yeah speed from the config.json doesn't work, i have too edit the app.js with speed to have effect.

**Comment by IgorAntun** [comment]
Then change it to read it from the config.json, please :)

**Comment by Crasha** [comment]
Oops, I meant 8 in what I said, not 7.

**Pull request merged**
