### PR TITLE
Implement spawn of viruses

### PR DESCRIPTION
**Pull request by CustomButtons**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166231688%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166671632%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/361%23issuecomment-166231688%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22It%20worked%20.%5Cr%5CnI%20think%20you%20should%20change%20fill%20and%20stroke%20%3A%20%5Cr%5Cn%5Ct%5C%22fill%5C%22%3A%20%5C%22%232EE62E%5C%22%2C%5Cr%5Cn%5Ct%5Ct%5C%22stroke%5C%22%3A%20%5C%22%233f3%5C%22%2C%5Cr%5CnThats%20the%20colors%20i%20captured%20inspecting%20the%20original%20game%20.%5Cr%5CnI%20could%20not%20sucessfully%20explode%20colliding%20with%20the%20virus%2C%20and%20the%20virus%20havent%20growed%2C%20even%20when%20i%20fired%20food%20on%20it%2C%20but%20i%20changed%20the%20food%2C%20fire%2C%20i%20changed%20all%20mass%20value%20%3AP%20%5Cr%5CnShould%20i%20test%20again%20%3F%22%2C%20%22created_at%22%3A%20%222015-12-21T08%3A29%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1096743%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/3642066%22%7D%7D%2C%20%7B%22body%22%3A%20%22what%27s%20holding%20back%20this%20pull%20request%20from%20being%20merged%20at%20this%20point%3F%22%2C%20%22created_at%22%3A%20%222015-12-22T16%3A51%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/419868%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TechJournalist%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/huytd/agar.io-clone/pull/361#issuecomment-166231688'>General Comment</a></b>
- <a href='https://github.com/3642066'></a> It worked .
I think you should change fill and stroke :
"fill": "#2EE62E",
"stroke": "#3f3",
Thats the colors i captured inspecting the original game .
I could not sucessfully explode colliding with the virus, and the virus havent growed, even when i fired food on it, but i changed the food, fire, i changed all mass value :P
Should i test again ?
- <a href='https://github.com/TechJournalist'></a> what's holding back this pull request from being merged at this point?

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/361?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/361?approve=1'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/361'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/361'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by 3642066** [comment]
It worked .
I think you should change fill and stroke : 
	"fill": "#2EE62E",
		"stroke": "#3f3",
Thats the colors i captured inspecting the original game .
I could not sucessfully explode colliding with the virus, and the virus havent growed, even when i fired food on it, but i changed the food, fire, i changed all mass value :P 
Should i test again ?

**Comment by TechJournalist** [comment]
what's holding back this pull request from being merged at this point?

**Comment by IgorAntun** [comment]
:shipit:

**Comment by IgorAntun** [comment]
@3642066 If you may, please open another PR with the mentioned changes, so I can merge it, thanks! :)

**Comment by Incognitov** [comment]
I've changed colour strokes to the ones suggested above by @3642066, however colours seem to flash randomly. Is that meant to happen?

**Comment by Incognitov** [comment]
@3642066, using what you suggested as the stroke will result in an invalid hexadecimal integer, and cause the game to use "rainbow" viruses. Instead of the web safe colour, use this: #33FF33.

**Comment by Incognitov** [comment]
@IgorAntun, the colours that @3642066 suggested contain an invalid hexadecimal colour. As a result, it causes the viruses to have a "rainbow" selection of colours.

**Comment by abalabahaha** [comment]
@Incognitov those are valid hexadecimal colors...

**Comment by Incognitov** [comment]
@abalabahaha, to an extent. The #3F3 colour suggested above resulted in the system recognising it as invalid. Instead of using this colour code, you must use #33FF33. This is the equivalent, however the system only interprets the latter as valid. You can try it yourself.

**Comment by abalabahaha** [comment]
I'm aware that shorthand hex is not strictly a color :3

**Comment by Incognitov** [comment]
Okay cool. :)

**Comment by 3642066** [comment]
Thank you for attention. I will help this project as much as i can .
I updated everything, and i made some new tests .

**Comment by 3642066** [comment]
I am reading the code, but as i sayd, i know websockets for a long time, but i could not understand how servers works yet, i could install this game and some other projects only because of git and deployment, but i already worked very hard to, for example, i have an App that publishes the canvas image into Facebook with one click, and I can implement Facebook Login for chaning the player name, for example.. And activities, sharing mass, and saving scores, if you just give me the variables i need to use .. i think this will help very much on final stages of game development .

**Comment by 3642066** [comment]
And i dont wanna sell this, u know? My propose here is learning with you, i have no idea of how could i help Virus, for example.. But i searched the code for the colors, seeing how it was defined, updated those changes into my server, and tested it .

**Comment by 3642066** [comment]
Thank you for attention .

**Comment by 3642066** [comment]
If you can, please help me using Github, giving me instructions of "where should i do what" .
I need to give a Feedback of last updates .. SOme weeks ago, the mass was not getting together after splitting, then, after update, the mass was getting together, but not with the correct total mass, so, i started feedbacking here. You updated, and the after split we have a correct total mass. Then, one player was not getting other smaller player, this is better now, but i noticed that if one player have a very small mass, and another player have a bigger mass, the small player can walk into the bigger one, and only if the small player passes into the CENTER of the bigg player's mass, he dies .
Thank you for your attention .

**Comment by 3642066** [comment]
If you can, please help me using Github, giving me instructions of "where should i do what", fell free to help me with that when you think its necessary, im not very organizated .
I need to give a Feedback of last updates .. SOme weeks ago, the mass was not getting together after splitting, then, after update, the mass was getting together, but not with the correct total mass, so, i started feedbacking here. You updated, and the after split we have a correct total mass. Then, one player was not getting other smaller player, this is better now, but i noticed that if one player have a very small mass, and another player have a bigger mass, the small player can walk into the bigger one, and only if the small player passes into the CENTER of the bigg player's mass, he dies .
I think you need consider the total mass of the cell on the function that eats players, i will call this "eating area", there is where is the problem now, the eating area is small, i think maybe is the mass size of staring player, and sometimes its very difficult to eat another player, if you change the configuration values for small starting mass, and more splitting limit, you can reproduce that, or you can test on my server, iogar, its already listed on project's wiki. (See how i'm learning it .. =])
I also tested some fixes made by another colaborator on player name, when no player name, its all ok, i checked all the code, so i could learn a litle. I think i need work with him on that, for implementing Facebook Login. Its simple, you will see .. 
Chat fixes are ok too, text is not disappearing anymore .. but characters limit is small and its very boring .

**Comment by 3642066** [comment]
When Agario implemented Facebook they walked into a great step on getting new users, and when they starting using XP the users come back, same score of before.. So, they stimulate login giving an starting mass for the users, and unfortunally turn to another way when started that monetizing everething all over the game. They could use more frictionless actions for sharing actions, activities, scores and exchange social actions into game store products, for keep development going ahead instead of the most commercial solluction possible. Anyway, they sill can socialize the game, and if that game platform help on that, it will be an awesome update . 
For this project, i think Facebook Login is nice for example, (as option) for giving names to the cells, or maybe drawing the profile picture as an skin? Yes its possible .
Its also good for in case of testing, no players are online, right ? 
Using Facebook we can send invites for other users, and that could return as many things . 
Free mass, speed, but that need to be implemented into final game development stage .

**Pull request merged**
