### PR TITLE
Add View Mass Mode ( #196 )

### PR DESCRIPTION
**Pull request by simon-matt**
Mass Mode now viewable via the ingame command "-mass".
The Mass is now easily visible at the end of the Player's name.
See more: https://github.com/huytd/agar.io-clone/issues/196

### CODE REVIEW

**Comment by IgorAntun** [comment]
Thank you so much for that :)

**Comment by themuddfamily2** [comment]
Don't you think -mass should be one of the options in the settings tab on the main menu?

**Comment by simon-matt** [comment]
What about giving the players both possibilities?
If you forgot to activate the mass Mode you can do it ingame and you can toggle it before you join the game.

**Comment by IgorAntun** [comment]
+1 for both the menu button and the chat command.

**Pull request merged**
