### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by hunterpl**
Hi there!

I translate for Polish users but I have request to add possibility change this files with keyboard "Polish Programmers" I can not edit this files from my keyboard and use a special characters from my alphabet. I have to copy and paste from ex. notepad so pathetic for me to edit some files.

### CODE REVIEW

**Comment by IgorAntun** [comment]
I can't merge this into our master branch since it'll translate the whole source, could you please put it in some kind of JSON maybe?

**Comment by hunterpl** [comment]
Hello Igor Can you split this file as you wish and named index-PL.html?

**Comment by jniles** [comment]
@hunterpl , thank you for providing a PL translation.  However, renaming files is not scalable.  Could you perhaps look into using a JSON key-value store for translation?   That way, a user could choose a language on start up, download the appropriate JSON (such as `fr.json` or `pl.json`) and translate all the text on the page.

You probably don't need an external library/framework, but here are some for inspiration:
http://i18next.com/
http://belelros.github.io/jqueryTranslator/
https://webtranslateit.com/en/docs/file_formats/json

**Comment by hunterpl** [comment]
@jniles What about make a folder languages?

there include the folders named ex:
en-GB
en-US
pl-PL
etc...

and into each folders make a files .json with menu.json, game.json, dm.json, tdm.json, lms,json etc... but I need someone who can just coding this and I will just translate on ready .json files.

**Comment by IgorAntun** [comment]
Closing this pull request since it won't be merged. Please continue this discussion on #149 :)

**Pull request closed without merging**
