### PR TITLE
Renderer polygons rather than arcs to be more like the original

### PR DESCRIPTION
**Pull request by danprince**
Renders players and food as many sided circular polygons, a bit more like the ones in the original.

### CODE REVIEW

**Comment by danprince** [comment]
Screenshot Attached

**Comment by huytd** [comment]
I like the food. But for players, do we need to render them as a polygon?
I prefer arc.
Let's see what everyone said :D

**Comment by themuddfamily2** [comment]
Agreed with huytd, the actual player cells in agar.io aren't really polygons, it just glitches sometimes and becomes one. I do like the food as polygons though.

**Comment by danprince** [comment]
They've got kind of a membrane which warps when they touch other cells, or the edges of the board. Could integrate the polygon players when someone wants to do the physics for that?

**Comment by danprince** [comment]
Going to split into two requests (food/players) and helps to keep local master cleaner.

**Comment by huytd** [comment]
Great :D

**Comment by IgorAntun** [comment]
Also, what about adding a random rotation to the food objects? Just so they don't look perfectly aligned to each other?

**Comment by danprince** [comment]
Implemented in PR #110

**Comment by IgorAntun** [comment]
Thanks!

**Pull request closed without merging**
