### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by vikramdurai**
A small change to make it that it outputs "localhost:{port}" or "127.0.0.1:{port}"
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/IgorAntun%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/flaminggenius%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/14892313%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/vikramdurai%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7627362%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-265991265%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-12-09T11%3A18%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7627362%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/vikramdurai%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-12-09T23%3A25%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/14892313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/flaminggenius%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-12-09T23%3A25%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/14892313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/flaminggenius%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-12-09T23%3A26%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/14892313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/flaminggenius%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222016-12-10T03%3A09%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5935946%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/IgorAntun%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-265991265%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-266150912%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-266150919%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-266151111%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/474%23issuecomment-266174949%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/IgorAntun'></a><a href='https://github.com/flaminggenius'></a><a href='https://github.com/vikramdurai'></a>

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/474?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/474?approve=0'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/474'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/474'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by vikramdurai** [comment]
:shipit:

**Comment by flaminggenius** [comment]
:shipit:

**Comment by flaminggenius** [comment]
:shipit:

**Comment by flaminggenius** [comment]
:shipit:

**Comment by IgorAntun** [comment]
:shipit:

**Comment by abalabahaha** [comment]
This is really misleading and shouldn't have been merged at all. If an IP address is passed to `http.listen()`, node will listen on that IP, not `localhost`. Otherwise, node would listen on `0.0.0.0` (or `::` on IPv6), not `127.0.0.1`.

**Pull request merged**
