### PR TITLE
Enforce code quality by intentionally killing gulp on error

### PR DESCRIPTION
**Pull request by JuhQ**
This PR is related to issue #255, it will intentionally kill gulp and prevent development until issues have been fixed.

This can be a pain in the ass first, but should improve the overall code quality on the long run.

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
You do realize that jshint has a `reporter('fail')` you can pipe to, right? That instantly fails the build when lint fails.

**Comment by IgorAntun** [comment]
Nice PR, but apparently Travis didn't like it as much, could someone please investigate why is that?
Apparently the map stream is causing it.

`map stream is not writable` at `agar.io-clone/node_modules/map-stream/index.js:90`

**Comment by MadaraUchiha** [comment]
@IgorAntun This whole PR can be summarized by adding one line. (pipe to `reporter(fail)`). I'll prepare a comparable PR.

**Comment by IgorAntun** [comment]
Okay, I'm gonna merge #257 and close this one then.
Thanks to you both @JuhQ @MadaraUchiha for helping :)

**Comment by JuhQ** [comment]
Well done @MadaraUchiha :) :+1:

**Pull request closed without merging**
