### PR TITLE
Chroot player in gamearea

### PR DESCRIPTION
**Pull request by villers**
min x = 0
min y = 0
max x = player.gameWidth
max y = player.gameHeight

### CODE REVIEW

**Comment by IgorAntun** [comment]
Could you please elaborate on this PR description explaining what exactly this will change, so others can check it easier later? Thanks :)

**Comment by villers** [comment]
This prevents the player to leave the playing area.

**Comment by IgorAntun** [comment]
Ok. I would suggest changing `player.y > 0 || player.y < 0` for `player.y !== 0`, and `player.y < player.gameHeight || player.y > player.gameHeight` for `player.y !== player.gameHeight`. Same for player.x/player.gameWidth.

**Comment by villers** [comment]
`player.x > 0`  move up to touch a corner left
`player.x < gameWidth` move up to touch a corner right

with your suggestion you have forgotten
**`player.x < 0 && deltaX > 0`**  move up to touch a corner left and mouse pointing to the right
**`player.x > player.gameWidth && deltaX < 0`** move up to touch a corner right and mouse pointing to the left

**Comment by IgorAntun** [comment]
I see. My point is that checking if something is lower or higher than 0 is basically checking if it's *not 0*, so using `!== 0` would give the same result in a simpler way :)

**Comment by villers** [comment]
what is your point  for   `(player.y > 0 || (player.y < 0 && deltaY > 0))` ?

**Comment by IgorAntun** [comment]
Ooooh nevermind me. I've misread your code. Merging it now, thanks for the PR and feel free to add yourself as a contributor in package.json :)

**Comment by villers** [comment]
no problem :+1:

**Pull request merged**
