### PR TITLE
minor find index and player refactor

### PR DESCRIPTION
**Pull request by bjarneo**
Changed playerID/foodID to ID.

### CODE REVIEW

**Comment by IgorAntun** [comment]
Any specific reason to use .ID instead of .id? Doesn't the lower case looks better?

**Comment by bjarneo** [comment]
Just followed the naming convention used in the code. I agree id feels and looks better.

**Comment by IgorAntun** [comment]
Could you please change it to .id then so I can merge it? Thanks :)

**Comment by bjarneo** [comment]
Done :)

**Comment by IgorAntun** [comment]
Thank you! Include yourself as a contributor on package.json if you may ;)

**Comment by bjarneo** [comment]
Sure :)

**Pull request merged**
