### PR TITLE
Fix some spacing mistakes

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by IgorAntun** [comment]
Thank you for the corrections!

**Comment by panpawn** [comment]
Np.

Also, I really don't know where to put this but I have a live demo that will continuously be up: http://ps-agar-panpawn1.c9.io/
@IgorAntun

**Comment by abalabahaha** [comment]
@panpawn Stuck it in the live servers list https://github.com/huytd/agar.io-clone/wiki/Live-Demos

**Comment by panpawn** [comment]
Thanks @abalabahaha

**Pull request merged**
