### PR TITLE
Did a little change

### PR DESCRIPTION
**Pull request by Max1Truc**
I increased the max default mass of the viruses.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Max1Truc%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/487%23issuecomment-289596325%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-03-27T21%3A47%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Max1Truc%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20know%20it%27s%20a%20very%20little%20change%20but%20I%20thought%20that%20it%27s%20important.%20%3A-%29%22%2C%20%22created_at%22%3A%20%222017-03-27T21%3A50%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/26603929%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Max1Truc%22%7D%7D%2C%20%7B%22body%22%3A%20%22Why%20change%20it%3F%20What%27s%20wrong%20with%20the%20current%20one%3F%22%2C%20%22created_at%22%3A%20%222017-03-28T02%3A46%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/2415829%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/abalabahaha%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/487%23issuecomment-289596325%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/487%23issuecomment-289597036%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/487%23issuecomment-289646559%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Max1Truc'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/huytd/agar.io-clone/pull/487#issuecomment-289596325'>General Comment</a></b>
- <a href='https://github.com/Max1Truc'></a> :shipit:
- <a href='https://github.com/Max1Truc'></a> I know it's a very little change but I thought that it's important. :-)
- <a href='https://github.com/abalabahaha'></a> Why change it? What's wrong with the current one?

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/487?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/487?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/487?approve=0'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/487'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/487'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Max1Truc** [comment]
:shipit:

**Comment by Max1Truc** [comment]
I know it's a very little change but I thought that it's important. :-)

**Comment by abalabahaha** [comment]
Why change it? What's wrong with the current one?

**Pull request closed without merging**
