### PR TITLE
Hide overflow in body

### PR DESCRIPTION
**Pull request by dotgodly**
Added `overflow:hidden` to fix the positioning issues caused by the leaderboard update.

Fixes: #515, #520

### CODE REVIEW

**Comment by AbdoelKaheal** [comment]
Yes can someone please merge this?

**Comment by dotgodly** [comment]
This repository isn’t being maintained anymore, you can grab the one from my profile if you want.

**Comment by dotgodly** [comment]
Yes, because it fixes the issue referenced here. 

The best part about open source is that you’re also welcome to fork the repository and maintain it.

**Comment by huytd** [comment]
The PR looks good to me (lol, ofcourse it looks good). Merging.

**Pull request merged**
