### PR TITLE
Change the mass under the name of the cell

### PR DESCRIPTION
**Pull request by CarlBarr**
Change the mass under the name of the cell
agar

### CODE REVIEW

**Comment by IgorAntun** [comment]
Awesome, thanks for the PR!

**Comment by abalabahaha** [comment]
Wait. Didn't we already implement this? We already had a feature where you type in -mass into the chatbox as a command. @IgorAntun

**Comment by abalabahaha** [comment]
whoops random clicks ignore that

This does make it look better, but the new initial font size is too small. The name is kind of legible, but the mass number is barely visible, and not legible.

**Comment by CarlBarr** [comment]
As the font size depends on the cell radius could be changed in util.js
```exports.massToRadius = function (mass) {
    return 4 + Math.sqrt(mass) * 6;
};```by
```exports.massToRadius = function (mass) {
    return 14 + Math.sqrt(mass) * 6;
};``` the size is similar to agar.io

**Comment by abalabahaha** [comment]
No the massToRadius is fine, it's the text size math that's the issue. I did something in #291 :3 Feel free to criticize my magical numbers, but I want something that people can read, not something that looks like an ant army on my screen.

**Pull request merged**
