### PR TITLE
Added npm test to tarvis file

### PR DESCRIPTION
**Pull request by RemoveIt**
#84 idk if I should fix errors from jshint in this PR

### CODE REVIEW

**Comment by RemoveIt** [comment]
Nvm I'm doing something wrong dont merge now

**Comment by huytd** [comment]
https://travis-ci.org/huytd/agar.io-clone/jobs/64931775
buidl failed :(

**Comment by RemoveIt** [comment]
because of errors from jshint

**Comment by huytd** [comment]
Ah, I see I see

**Pull request closed without merging**
