### PR TITLE
Cell speed

### PR DESCRIPTION
**Pull request by VytorCalixto**
Based on SarenCurrie/agar.io-clone@a7182b9 

Closes: huytd/agar.io-clone#30

### CODE REVIEW

**Comment by IgorAntun** [comment]
Are you sure using prototypes would be a better way to handle this? Also, has this been thoroughly tested?

**Comment by D3VONT3CH** [comment]
Live demo at:
https://agar-io-clone-d3vont3ch.c9.io/
igor, please remove the demo of openshift

**Comment by IgorAntun** [comment]
@D3VONT3CH Ok.

**Comment by IgorAntun** [comment]
Also please check https://github.com/PETComputacaoUFPR/agar.io-clone/commit/0ef7806766286732f733caaa77629a4a8e32d3bc#commitcomment-11368995

**Comment by VytorCalixto** [comment]
Commits e81c6bb and 31e1223 refactored the code to actual standarts. The older commits are from @SarenCurrie and other merges. This pull request itself only adds the lines 80 to 93 and 142, that is, the movePlayer function.

**Comment by IgorAntun** [comment]
Merged. Thanks :)

**Pull request merged**
