### PR TITLE
Add gulp task to automatically add contributors to package.json

### PR DESCRIPTION
**Pull request by huytd**
**Need to review**

---

There are many contributors has joined and help the project now (many thanks to all of you, guys!)

But the `contributors` section in `package.json` has been stopped updating for a long time. 

In the beginning, we asked contributors to add their name into this section manually, but time goes on, some of the new contributors didn't know about that so they didn't put their name in. 

I created a new `gulp` task to do this automatically. Run it with: 

```
gulp contributors
```

This will call some Github API and update `package.json` 

Didn't tested this code yet because I'm now reaching the call limit of the API, so I pushed it here, somebody please help me test the output `package.json` if it has any damage or not.

I will be able to test the API again at next 8 hours :sob: Didn't paid for *Github Developer Program* yet.

Thank you so much everybody!
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/378%23issuecomment-176324186%22%2C%20%22https%3A//github.com/huytd/agar.io-clone/pull/378%23issuecomment-176335320%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/378%23issuecomment-176324186%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Out%20of%20curiosity%2C%20does%20NPM%20do%20anything%20with%20the%20contributors%20info%3F%20Is%20it%20searchable%20or%20hold%20any%20value%3F%20Reason%20why%20I%20ask%20is%20it%20may%20serve%20more%20of%20a%20purpose%20for%20visibility%20if%20it%20was%20on%20a%20wiki%20page%20and%20linked%20to%20by%20the%20%60Readme.md%60%3F%20If%20it%20holds%20a%20value%20with%20NPM%20then%20I%20can%20use%20something%20like%20https%3A//www.npmjs.com/package/contributor%20for%20the%20es6%20version.%22%2C%20%22created_at%22%3A%20%222016-01-28T18%3A28%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8633146%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/underGhost%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yeah%20we%20can%20do%20some%20thing%20with%20the%20contributor%20list%20in%20%60package.json%60%2C%20for%20example%2C%20generate%20the%20contributor%20page%20or%20something%2C...%20npm%20can%20see%20the%20contributor%20list%20with%20%60npm%20view%60%5Cr%5Cn%5Cr%5CnIt%27s%20always%20a%20good%20idea%20to%20keep%20the%20contributor%20list%20updated.%20To%20show%20the%20respect%20of%20the%20community%20to%20them%20%3AD%20%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-01-28T18%3A51%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/613943%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/huytd%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/huytd/agar.io-clone/pull/378#issuecomment-176324186'>General Comment</a></b>
- <a href='https://github.com/underGhost'></a> Out of curiosity, does NPM do anything with the contributors info? Is it searchable or hold any value? Reason why I ask is it may serve more of a purpose for visibility if it was on a wiki page and linked to by the `Readme.md`? If it holds a value with NPM then I can use something like https://www.npmjs.com/package/contributor for the es6 version.
- <a href='https://github.com/huytd'></a> Yeah we can do some thing with the contributor list in `package.json`, for example, generate the contributor page or something,... npm can see the contributor list with `npm view`
It's always a good idea to keep the contributor list updated. To show the respect of the community to them :D

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/378?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/378?approve=1'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/378'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/378'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by underGhost** [comment]
Out of curiosity, does NPM do anything with the contributors info? Is it searchable or hold any value? Reason why I ask is it may serve more of a purpose for visibility if it was on a wiki page and linked to by the `Readme.md`? If it holds a value with NPM then I can use something like https://www.npmjs.com/package/contributor for the es6 version.

**Comment by huytd** [comment]
Yeah we can do some thing with the contributor list in `package.json`, for example, generate the contributor page or something,... npm can see the contributor list with `npm view`

It's always a good idea to keep the contributor list updated. To show the respect of the community to them :D

**Comment by huytd** [comment]
finally... :heart:

**Pull request merged**
