### PR TITLE
Update Bluemix EU status to online.

### PR DESCRIPTION
**Pull request by Buskcoin**
This is from pr/#268 but I figured we may as well show it online since it's up to date. Bluemix US isn't working for me anymore for some reason so i left that one as is.

### CODE REVIEW

**Comment by abalabahaha** [comment]
Note: I tried to merge juslee's bluemix fix in my hotfix PR, so merge that one before this and there shouldn't be any conflicts.

**Comment by IgorAntun** [comment]
Bummer, got merge conflicts anyway... :(

**Comment by abalabahaha** [comment]
Ahh oops :/ Thought keeping the modified liens the same wouldn't make it fail

**Comment by Buskcoin** [comment]
It's alright. it's only one line. I'll fix it.

**Comment by Buskcoin** [comment]
This is ready to merge now.

**Comment by IgorAntun** [comment]
Awesome!

**Pull request merged**
