### PR TITLE
Full client side ES6 rewrite

### PR DESCRIPTION
**Pull request by danprince**
Probably needs a lot of debugging still, but all of the core functionality has been modularised and rewritten as ES6.

Having problems with Gulp (#127) if we can get this merged into the branch, then anyone trying to fix can test with the actual code.

### CODE REVIEW

**Comment by huytd** [comment]
Awesome :+1: I'm not brave enough to click the Merge button :trollface: 
Come and check with me guys!!!!

**Comment by danprince** [comment]
It's still a way off. Sorting out the renderer now, I'll let you know when it's ready for people to start testing functionality.

**Comment by danprince** [comment]
Going to suggest that we merge this with the es6-refactor branch now, even though it's still broken. Could do with some help from someone who was involved with writing the initial rendering code.

Stuff is rendered, but there's no movement. As far as I can see, the player sends the target up every time, the server moves the `currentPlayer` then we send the new details back down the socket so that the player can update.

The target is acquired correctly (it seems) and sent to the server. The server already has a reference to currentPlayer. `movePlayer` gets called with both and at that point we end up with bad values and the player doesn't move.

Might be something dead simple, but I've spent waaay too long looking at it today. Leaving this here for someone else to pick up this evening, or I'll have another go tomorrow.

**Comment by IgorAntun** [comment]
I'm not really familiar with both ES6 and the render code, so I'm gonna leave it up to someone else :)
Thanks for all your hard work on that, though!

**Pull request merged**
