### PR TITLE
Update enemy rendering, players who haven't eaten cannot be eaten again, large mass blobs on top.

### PR DESCRIPTION
**Pull request by Buskcoin**
I changed the enemy rendering to be like drawPlayer. 
The player/enemy with larger mass will come out on the foreground.
mass loss won't drop below 10.
Players who haven't eaten won't be checked for collisions.

### CODE REVIEW

**Comment by IgorAntun** [comment]
That's awesome, but could you pretty please try to fix the merge conflicts on it? Thanks in advance :)

**Comment by Buskcoin** [comment]
definitely

**Comment by JuhQ** [comment]
@Buskcoin please run `gulp lint-client` and `gulp lint-server` and fix accordingly.

**Comment by Buskcoin** [comment]
Ok, should be good to merge.

**Pull request merged**
