### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by villers**
optimizing playerJoin

### CODE REVIEW

**Comment by IgorAntun** [comment]
Tested and working?

**Comment by villers** [comment]
Yes

**Comment by villers** [comment]
http://socket.io/docs/#sending-and-receiving-events

// note, io(<port>) will create a http server for you
var io = require('socket.io')(80);

io.on('connection', function (socket) {
  io.emit('this', { will: 'be received by everyone'});

  socket.on('private message', function (from, msg) {
    console.log('I received a private message by ', from, ' saying ', msg);
  });

  socket.on('disconnect', function () {
    io.emit('user disconnected');
  });
});

**Comment by IgorAntun** [comment]
Ok, thanks. Feel free to add yourself as a contributor on package.json if you may ;)

**Pull request merged**
