### PR TITLE
Mobile optimisation, and improvements

### PR DESCRIPTION
**Pull request by Incognitov**
Hey! This is quite an update, but there really isn't much to it:

- Added buttons for mobile with the support of jQuery, which allow for
splitting and feeding.
- Added an images folder, which contains images for the mobile buttons
courtesy of @matrixreal, thank you very much.
- More typographical improvements.
- More styling for the buttons and responsiveness.
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/366?approve=1'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/366'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/366'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by matrixreal** [comment]
Hi,
wow ... can believe ... any link to test ?
and wish you the best for the new year

**Comment by Incognitov** [comment]
Hey @matrixreal! I hope you have a great new year too! I hope you're okay with me using your images? But yeah, if you'd like to test it you can test it here: http://sys35537.leet.cc.

**Comment by matrixreal** [comment]
@Incognitov 
great great great manand i see that performance are good really ...
stil need some improvements i will post later a list :dancer: 
but it's not urgent

**Comment by CakeSlayer** [comment]
Cool, Would love to hear any improvements/sugegstions, Me and incognito are also working on improving viruses and adding skins. :P

**Comment by IgorAntun** [comment]
:shipit:

**Comment by Incognitov** [comment]
@matrixreal, that would be helpful thanks.

**Comment by 3642066** [comment]
Wow, this one, nlue color is awesome, with music, WOw .. 
I loved that .

**Comment by Incognitov** [comment]
Oh, are you talking about my hosted version? :)

**Pull request merged**
