### PR TITLE
Openshift version

### PR DESCRIPTION
**Pull request by D3VONT3CH**

### CODE REVIEW

**Comment by huytd** [comment]
Hello @D3VONT3CH 

I think it would be better if we merge the current code with your code, because the main change for OpenShift is `process.env.OPENSHIFT_NODEJS_PORT` and ` process.env.OPENSHIFT_NODEJS_IP`

**Comment by IgorAntun** [comment]
Yeah I think it would be better to just add that to the original source. Also, please note I added those `"` between badges for aesthetical purposes, it just looks better with those.

**Comment by D3VONT3CH** [comment]
huytd, you cant test if my code works without openshift?

**Comment by D3VONT3CH** [comment]
igorantun, i edited the code added "&nbsp;&nbsp;", this is better than ", no?

**Comment by IgorAntun** [comment]
I think `"` is simpler. @huytd opinions?

**Comment by D3VONT3CH** [comment]
right, i agree with you, now the problem is the code.

**Comment by IgorAntun** [comment]
I think changing https://github.com/huytd/agar.io-clone/blob/master/server.js#L9 to `var serverPort = process.env.OPENSHIFT_NODEJS_PORT || process.env.PORT || 3000;` instead of `var serverPort = process.env.PORT || 3000;` would solve the problem, wouldn't it?

**Comment by D3VONT3CH** [comment]
@huytd & @IgorAntun
you are right, but i think the problem is that huytd don't have ip

**Comment by D3VONT3CH** [comment]
http://pastebin.com/WGVpabjS

i think this can solve the problem, i am testing on my site.

**Comment by D3VONT3CH** [comment]
i tried, but only my code worked

**Comment by D3VONT3CH** [comment]
@IgorAntun  now works in openshift, try to test my server.js in other host
the code that you posted worked, i added ip to code, @huytd  now if work in other host
you can merge.

**Comment by D3VONT3CH** [comment]
close this, i will made a new request.

**Pull request closed without merging**
