### PR TITLE
Set default mass to 10

### PR DESCRIPTION
**Pull request by Buskcoin**
I noticed that new players couldn't be eaten and adjusted the default mass to 10.

### CODE REVIEW

**Comment by bjarneo** [comment]
Gameplay Rules

Players who haven't eaten yet cannot be eaten

**Comment by Buskcoin** [comment]
woops

**Comment by hunterpl** [comment]
@bjarneo You mean about spawn protection. Good Idea.

**Comment by bjarneo** [comment]
Just following @huytd rules :+1:

**Pull request closed without merging**
