### PR TITLE
Players don't lose mass below 10, cosmetics, add random mass to food object.

### PR DESCRIPTION
**Pull request by Buskcoin**
I made it look and feel more like agar.io. Changed the grid and background color and the player size a little.  Players wont lose mass when they haven't eaten anymore. I added mass to the food object in server.js(I also made it slightly random). I adjusted the speed a little. I also changed the name of the "contain" function to "valueInRange".

### CODE REVIEW

**Comment by abalabahaha** [comment]
Just a recommendation, change your git name on your computer to your GitHub username instead of "my name" so GitHub actually attributes commits to your account. I think it's
```
git config --global user.name "Buskcoin"
```

**Comment by abalabahaha** [comment]
And I think food rendering could be improved to look more like the original by changing client/js/app.js:110 to "foodMass": 1, as by default the server config is foodMass: 1

**Comment by Buskcoin** [comment]
Thanks for the feedback. I didn't realize i wasnt getting any credit ;). I'll check out the food mass next time I get a chance.

**Comment by abalabahaha** [comment]
Nvm, #235 got there first

**Comment by IgorAntun** [comment]
Awesome!

**Pull request merged**
