### PR TITLE
bump nodejs/npm dependencies

### PR DESCRIPTION
**Pull request by PeterDaveHello**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/huytd/agar.io-clone/pull/428%23issuecomment-223585964%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/huytd/agar.io-clone/pull/428%23issuecomment-223585964%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Nice%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-06-03T13%3A58%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10373452%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RLEXBuilding%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/huytd/agar.io-clone/pull/428#issuecomment-223585964'>General Comment</a></b>
- <a href='https://github.com/RLEXBuilding'></a> Nice

<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/428?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/huytd/agar.io-clone/pull/428?approve=1'></a>&nbsp;<a href='https://github.com/huytd/agar.io-clone/pull/428'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by huytd** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/huytd/agar.io-clone/pull/428'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by RLEXBuilding** [comment]
Nice

**Comment by PeterDaveHello** [comment]
hmmmm ... though it passed the test, seems there is a problem in browser console, and I can't click the "play button" now:
`SyntaxError: export declarations may only appear at top level of a module`

**Comment by abalabahaha** [comment]
Interesting... might be a breaking change in the Babel 5 -> 6 upgrade

**Comment by PeterDaveHello** [comment]
Seems so, so sent #430 first.

**Pull request merged**
